/// Flutter icons Nav_icons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Nav_icons
///      fonts:
///       - asset: fonts/Nav_icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Nav_icons {
  Nav_icons._();

  static const _kFontFam = 'Nav_icons';
  static const String? _kFontPkg = null;

  static const IconData bookmark = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statistics__1_ = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
